services:
  app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    container_name: "heavy-division-bot"
    secrets:
      - discord_token
      - metar_token
      - station_token
    environment:
      DEBUG_MODE: true
      NODE_ENV: development # development | production
      BAN_APPEAL_URL: "https://google.com"
      LOG_LEVEL: "DEBUG"
      DISCORD_TOKEN: /run/secrets/discord_token
      METAR_TOKEN: /run/secrets/metar_token
      STATION_TOKEN: /run/secrets/station_token

secrets:
  discord_token:
    file: ./secrets/DISCORD_TOKEN.txt
  metar_token:
    file: ./secrets/METAR_TOKEN.txt
  station_token:
    file: ./secrets/STATION_TOKEN.txt